[build]
  publish = "src/build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

# Combined build commands
[build.commands]
  command = "npm install && cd src && npm install && npm run build"

# SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
